on: [push, pull_request]

jobs:

  lint-frontend:

  runs-on: ubuntu-latest
  name: Lint HTML, CSS, and JS
  steps:
    -
    - uses: actions/checkout@v3

    - name: Set up Node.js

    with:
      node-version: '18'

